server:
  port: ${PORT:8081}

spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}

whatsapp:
  access-token: ${WHATSAPP_ACCESS_TOKEN}
  phone-number-id: ${WHATSAPP_PHONE_NUMBER_ID}
  verify-token: ${WHATSAPP_VERIFY_TOKEN}